"use strict";
let places = ['Itlay', 'Germany', 'Agra', 'Eifel Tower', 'Times Square',];
console.log('Original ' + places);
console.log('copy ' + [...places].sort());
console.log('Original ' + places);
console.log('copy ' + [...places].sort().reverse());
console.log('Original ' + places);
console.log('copy ' + [...places].sort().reverse());
console.log('Original ' + places);
console.log('Original ' + places.reverse());
console.log('Original ' + places.reverse());
console.log('Original ' + places.sort().reverse());
