"use strict";
let car = 'subaru';
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car != 'Honda'? I predict True.");
console.log(car != 'Honda');
console.log("Is car !== 'ford'? I predict True.");
console.log(car !== 'ford');
console.log("Is car.Upper case == 'SABARU'? I predict True.");
console.log(car.toUpperCase() == 'SABARU');
console.log("Is car.lower Case == 'SABARU'? I predict False.");
console.log(car.toLowerCase() == 'SABARU');
console.log("Is car === 'SABARU'? I predict False.");
console.log(car === 'SABARU');
console.log("Is car === 'Train'? I predict False.");
console.log(car === 'Train');
console.log("Is car === 'Bus'? I predict False.");
console.log(car === 'Bus');
console.log("Is car === 'Cycle'? I predict False.");
console.log(car === 'Cycle');
